### ISSUE TITLE
ㅤ

### ISSUE THREAD

**Issue by R0rt1z2** [bq/aquaris-U-Lite#1]
~

**Comment by jmpfbmx** [comment]
And for when oreo kernel source?

**Comment by Kra1o5** [comment]
Hi @R0rt1z2, 
Source seems to be fine.
I think you have problems with toolchains.

@jmpfbmx,
U Lite doesn't have a O firmware yet.

**Comment by R0rt1z2** [comment]
~

**Comment by Kra1o5** [comment]
@R0rt1z2 ,
ok, probably Google changed master branch of toolchain and probably now it doesn't works, I think using N branch of the toolchain will fix the issue too, without need patches.

**Comment by R0rt1z2** [comment]
~

**Comment by jmpfbmx** [comment]
@Kra1o5 can you help on kernel upstreaming?
